

# This file was *autogenerated* from the file simple_trace_printer.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0)#A = load('./fema_modnull_constraints_traces.sobj')
#A = load('./fema_mod1_constraints_traces.sobj')
#A = load('./fema_mod2_constraints_traces.sobj')
#A = load('./fema_mod3_constraints_traces.sobj')
#A = load('./stakeholder1_mod1_traces.sobj')
#A = load('./stakeholder1_mod2_traces.sobj')
#A = load('./stakeholder1_mod3_traces.sobj')
#A = load('./stakeholder1_modnull_traces.sobj')
#A = load('./stakeholder2_mod1_traces.sobj')
#A = load('./stakeholder2_mod2_traces.sobj')
#A = load('./stakeholder2_mod3_traces.sobj')
#A = load('./stakeholder2_modnull_traces.sobj')
#A = load('./stakeholder3_mod1_traces.sobj')
#A = load('./stakeholder3_mod2_traces.sobj')
#A = load('./stakeholder3_mod3_traces.sobj')
A = load('./stakeholder3_modnull_traces.sobj')
number=_sage_const_0 
for x in A:
	print(x) # for python3

